name: Check & Release Workflow

on: [push]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v1.1.1
        with:
          bun-version: latest

      - name: Install dependencies
        id: install_code
        run: bun install --frozen-lockfile

  #      - name: Setup test environment
  #        run: cp .env.test .env
  #
  #      - name: Run tests
  #        run: bun test

  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: check
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup bun
        uses: oven-sh/setup-bun@v1.1.1
        with:
          bun-version: latest

      - name: Install dependencies
        id: install_code
        run: bun install --frozen-lockfile

      - name: Build
        id: build_code
        run: bun run build

      - name: Publish package
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
